### ISSUE TITLE
您好，请问一下有没有验证token的方法

### ISSUE THREAD

**Issue by zhuye-yichu** [pkg6/think-auth#20]
使用这种方法`$token = auth()->user()->createToken("test-token");`创建token后，有没有直接通过前端发送的请求头里获取后验证token是否一致的方法，另外可以设置token过期时间吗。

还有，如果我使用`Auth::login(User::find(1));`登录的时候，能够登录成功，没有返回token(也没有创建token到数据库)，这是正常的吗。

**Comment by zzqqw** [comment]
token 验证： https://github.com/pkg6/think-auth/blob/694195bd583d5476d20fca1b28a76059458f8969/src/sanctum/Guard.php#L89


token过期：在auth配置中添加一个配置 sanctum.expiration来设置过期

login 在在session中是一个方法返回的是void，没有返回值，可以通过事件来监听登录成功的用户信息https://github.com/pkg6/think-auth/blob/694195bd583d5476d20fca1b28a76059458f8969/src/events/Login.php#L19

**Comment by zzqqw** [comment]
如果您觉得我回答的还满意，可以关闭issues吗
